---
title: "GSE pull and parse"
author: "Luke Torre-Healy"
date: "5/22/2019"
output: html_document
---
This file is not to be knit, but to breakdown the accession, unzip, and parsing of GSE where the raw data is contained in supplement

```{r geoquery}
library(GEOquery)
a <- getGEO("GSE125588")
b <- a$GSE125588_series_matrix.txt.gz$geo_accession

for (i in b){
  getGEOSuppFiles(i, baseDir = "../extdata")
}
d <- c("../extdata/GSM3577882", "../extdata/GSM3577883", 
       "../extdata/GSM3577884", "../extdata/GSM3577885", "../extdata/GSM3577886")
c <- list.files("../extdata/GSM3577882")
```

```{r unzip}
for (i in d){
    c <- list.files(i)
    for (j in c){
        gunzip(paste(i,j, sep = "/"))
    }
}
```

```{r GSM3577882 parse}
library(Matrix)
library(readr)
normalpanc.m <- readMM("../extdata/GSM3577882/GSM3577882_normal_panc_matrix.mtx")

genes <- read_delim("../extdata/GSM3577882/GSM3577882_normal_panc_genes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
barcodes <- read_delim("../extdata/GSM3577882/GSM3577882_normal_panc_barcodes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
rownames(normalpanc.m) <- genes$X2
colnames(normalpanc.m) <- barcodes$X1

saveRDS(normalpanc.m, file = "../../data/GSM3577882_parsed.rds")
```

```{r GSM3577883 parse}
library(Matrix)
library(readr)
earlyKIC.m <- readMM("../extdata/GSM3577883/GSM3577883_early_KIC_matrix.mtx")

genes <- read_delim("../extdata/GSM3577883/GSM3577883_early_KIC_genes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
barcodes <- read_delim("../extdata/GSM3577883/GSM3577883_early_KIC_barcodes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
rownames(earlyKIC.m) <- genes$X2
colnames(earlyKIC.m) <- barcodes$X1

saveRDS(earlyKIC.m, file = "../../data/GSM3577883_parsed.rds")
```

```{r GSM3577884 parse}
library(Matrix)
library(readr)
lateKIC.m <- readMM("../extdata/GSM3577884/GSM3577884_late_KIC_matrix.mtx")

genes <- read_delim("../extdata/GSM3577884/GSM3577884_late_KIC_genes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
barcodes <- read_delim("../extdata/GSM3577884/GSM3577884_late_KIC_barcodes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
rownames(lateKIC.m) <- genes$X2
colnames(lateKIC.m) <- barcodes$X1

saveRDS(lateKIC.m, file = "../../data/GSM3577884_parsed.rds")
```

```{r GSM3577885 parse}
library(Matrix)
library(readr)
lateKPfC.m <- readMM("../extdata/GSM3577885/GSM3577885_late_KPfC_matrix.mtx")

genes <- read_delim("../extdata/GSM3577885/GSM3577885_late_KPfC_genes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
barcodes <- read_delim("../extdata/GSM3577885/GSM3577885_late_KPfC_barcodes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
rownames(lateKPfC.m) <- genes$X2
colnames(lateKPfC.m) <- barcodes$X1

saveRDS(lateKPfC.m, file = "../../data/GSM3577885_parsed.rds")
```

```{r GSM3577886 parse}
library(Matrix)
library(readr)
lateKPC.m <- readMM("../extdata/GSM3577886/GSM3577886_late_KPC_matrix.mtx")

genes <- read_delim("../extdata/GSM3577886/GSM3577886_late_KPC_genes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
barcodes <- read_delim("../extdata/GSM3577886/GSM3577886_late_KPC_barcodes.tsv", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
rownames(lateKPC.m) <- genes$X2
colnames(lateKPC.m) <- barcodes$X1

saveRDS(lateKPC.m, file = "../../data/GSM3577886_parsed.rds")
```