---
title: "plotExp4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

### Makes plots to evaluate deconvolution methods on Experiment 4
#### Obtain trueW and resultW from each deconvolution method

```{r}

load("~/rnaGinesis/data/exp4.RData")

load("~/rnaGinesis/data/exp4.NMF.result.RData")
# make fake trueH for experiment 4 for the rearrange function
experiment4$trueH <- exp4.NMF$resultH

exp4.NMF <- rearrange(exp4.NMF, experiment4)

resultW.NMF <- exp4.NMF[[1]]

trueW <- experiment4$trueW
trueH <- experiment4$trueH

```


#### Creates W.COSDIST with COSDIST between true cell-type specific gene expression profiles and estimated gene expression profiles for each sample
```{r}

W.COSDIST <- as.matrix(evalW.COSDIST(trueW,resultW.NMF))
colnames(W.COSDIST) <- c("NMF")
```

#### Graphs violin plots with W.COSDIST values from each deconvolution method
```{r}
# melts W.COSDIST into dataframe with two variables, method (1 = CIBERSORT, 2 = NMF) and W.COSDIST across all samples for each deconvolution method 
mydf2 <- reshape2::melt(W.COSDIST)
mydf2 <- mydf2[,-1]

names(mydf2) <- c("method", "W_COSDIST") 

# plots W.COSDIST between true W and estimated W in each sample based on deconvolution method
# make jitter reproduceable
set.seed(1234)
p2 <- ggplot2::ggplot(data = mydf2, ggplot2::aes(y = W_COSDIST, x= method, fill = method))
p2 <- p2 + ggplot2::geom_violin()
p2 <- p2 + ggplot2::geom_jitter(width = 0.1, height = 0) 
p2 <- p2 + ggplot2::ylim(0,1.5) 
p2 <- p2 + ggplot2::labs(title="Violin Plots of Cosine Distance (COSDIST) for Gene Expression",
                         x = "Deconvolution Method", 
                         y = "W_COSDIST") 
p2 <- p2 + ggplot2::theme(axis.title.x = ggplot2::element_text(size = 40)) 
p2 <- p2 + ggplot2::theme(axis.title.y = ggplot2::element_text(size = 40)) 
p2 <- p2 + ggplot2::theme(axis.text=ggplot2::element_text(size=30))

print(p2)
```