---
title: "makeExp1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#### Creates simulated data with 3 compartments, sample size = 50, noise_setting = 0
```{r}
Samplesize = 50
scaleFactor = rep(30, 2)
noise_setting = 0
d.params = c("Tumor"   = .3,
             "Stromal" = .5,
             "Normal"  = .2)
sim.data <- Complete_simulation(A_tumor = A,
                               mu_tumor = mu, 
                               Samplesize = Samplesize,
                               scaleFactor = scaleFactor,
                               d.params = d.params,
                               noise_setting = noise_setting,
                               seed = 1234)
names(sim.data) = c("Y", "W", "H", "Wi")
```

#### Obtains expression matrix with mixture data, trueW, trueH, signature matrices 
```{r}
ex <- sim.data[[1]]
meanW <- sim.data[[2]]
trueH <- sim.data[[3]]
trueW <- sim.data[[4]]

# Obtains unmixed/original gene expression profiles for each cell type
unmixed <- list()
for(i in 1:3) {
  unmixed[[i]] <- meanW[,i]
}

experiment1 <- list()
experiment1$ex <- ex
experiment1$trueW <- trueW
experiment1$trueH <- trueH
experiment1$unmixed <- unmixed 
```

#### Saves experiment1 data to .RData file
```{r}
save(experiment1, file = "/Users/anandbanwasi/Desktop/stonybrook/simons/moffitt/src/pdac/data/exp1.RData")
```