---
title: "run2.CIBERSORT"
output: html_document
---


## R Markdown

```{r}
#loads from .RData and creates matrices
load("~/rnaGinesis/data/exp2.RData")
sig_mat = experiment2$unmixed
#sig_mat = cbind(sig_mat[[1]], sig_mat[[2]], sig_mat[[3]])
mixt = experiment2$ex
rownames(mixt) <- c()
rownames(sig_mat) <- c()
# sig_mat
# save(sig_mat, file = "~/rnaGinesis/data/exp1_sigmat.txt")
write.table(sig_mat, "~/rnaGinesis/data/exp2_sigmat.txt", sep="\t")
write.table(mixt, "~/rnaGinesis/data/exp2_mixt.txt", sep="\t")
# save(mixt, file = "~/rnaGinesis/data/exp1_mixt.txt")
```

```{r}
q <- as.matrix(rownames(experiment2$ex))
# print(c)
write.table(q, "~/rnaGinesis/data/exp2_subset.txt", sep="\t", row.names = FALSE, col.names = FALSE)
```


## Go to https://cibersortx.stanford.edu and run CIBERSORTX. You may have to create an account beforehand.
## Remember to insert a name for the column that is the row names in both txt files 
## Upload the signature matrix and the expression matrix. 
## Run CIBERSORTX
## download results
## the W is "CIBERSORTx_JobN_GEP"
## the H is "CIBERSORTx_JobN_Fractions"
## move both files into the /data directory

```{r}
#reads W and H from files and saves as .RData file 
# exp1.CIBERSORT$H
exp1.CIBERSORT <- list()
exp1.CIBERSORT$resultH <- as.matrix(read.delim("~/rnaGinesis/data/CIBERSORTxGEP_Job22_Fractions.txt", header = TRUE, sep = "\t"))
col1 <- exp1.CIBERSORT$resultH[,1]
exp1.CIBERSORT$resultH <- data.matrix(read.delim("~/rnaGinesis/data/CIBERSORTxGEP_Job22_Fractions.txt", header = TRUE, sep = "\t"))
exp1.CIBERSORT$resultH <- exp1.CIBERSORT$resultH[,2:7]
rownames(exp1.CIBERSORT$resultH) <- col1
exp1.CIBERSORT$resultH <- t(exp1.CIBERSORT$resultH)

# exp1.CIBERSORT$W
exp1.CIBERSORT$resultW <- as.matrix(read.delim("~/rnaGinesis/data/CIBERSORTxGEP_Job22_GEPs.txt", header = TRUE, sep = "\t"))
col1 <- exp1.CIBERSORT$resultW[,1]
exp1.CIBERSORT$resultW <- data.matrix(read.delim("~/rnaGinesis/data/CIBERSORTxGEP_Job22_GEPs.txt", header = TRUE, sep = "\t"))
exp1.CIBERSORT$resultW <- exp1.CIBERSORT$resultW[,2:4]
rownames(exp1.CIBERSORT$resultW) <- col1
exp2.CIBERSORT <- exp1.CIBERSORT

exp2.CIBERSORT$resultW <- lapply(seq_len(ncol(exp2.CIBERSORT$resultH)), function(X) exp2.CIBERSORT$resultW)


save(exp2.CIBERSORT, file = "~/rnaGinesis/data/exp2.CIBERSORT.result.RData")

```

